name: pp_env
channels:
  - conda-forge
dependencies:
  - arviz
  - jupyter
  - matplotlib
  - numba
  - numpy<2
  - nutpie
  - openpyxl
  - pip
  - pymc
  - python=3.11
  - pip:
    - peak-performance
